### ISSUE TITLE
 I can't build

### ISSUE THREAD

**Issue by mabite44** [afulsamet/blockpost-uc#1]
I am a novice can you describe to me how we build all this 
please

**Comment by anzenchitai** [comment]
You still have a long way to go my dude. Unfortunately, I think that you won't find any help here :(

**Comment by mabite44** [comment]
why don't you give me some help

**Comment by anzenchitai** [comment]
[Follow this guide.](http://letmegooglethat.com/?q=how+to+compile+a+c%2B%2B+program)

**Comment by afulsamet** [comment]
You don't need to build the project, if you want to reach [binaries](https://github.com/afulsamet/blockpost-uc/releases).

**Comment by mabite44** [comment]
C:\Users\Nigga\Desktop\blockpost-uc-master\Hooks.cpp(1,10): fatal error C1083: Cannot open include file : 'Includes.h' : No such file or directory

C:\Users\Nigga\Desktop\blockpost-uc-master\Main.cpp(1,10): fatal error C1083: Cannot open include file : 'Includes.h' : No such file or directory

**Comment by afulsamet** [comment]
- Make sure you have Desktop development with C++, Windows SDK 10.0 and Visual Studio 2019 (v142) Build tools.
- Clone with git 
  - `git clone https://github.com/afulsamet/blockpost-uc.git`
- Open `.vcxproj` project and just build

**Comment by anzenchitai** [comment]
Try to include it with quotation marks instead of angle brackets.
